### ISSUE TITLE
Inconsistent Triggering

### ISSUE THREAD

**Issue by mattyjones** [adafruit/Adafruit_CircuitPython_LIFX#4]
```
code.py output:
Failed to connect, retrying
 ('No such ssid', b'ORBI64')
Traceback (most recent call last):
  File "code.py", line 38, in <module>
  File "adafruit_lifx.py", line 181, in list_lights
  File "adafruit_esp32spi/adafruit_esp32spi_requests.py", line 110, in json
ValueError: syntax error in JSON
```
or 

```
code.py output:
Failed to connect, retrying
 ('No such ssid', b'ORBI64')
Count:  0
Turning on light...
Setting light to:  yellow
Setting light to:  blue
Setting light to:  white
Turning off light...
Traceback (most recent call last):
  File "code.py", line 60, in <module>
  File "adafruit_lifx.py", line 128, in toggle_light
  File "adafruit_lifx.py", line 88, in _post
  File "adafruit_esp32spi/adafruit_esp32spi_wifimanager.py", line 129, in post
  File "adafruit_esp32spi/adafruit_esp32spi_requests.py", line 239, in post
  File "adafruit_esp32spi/adafruit_esp32spi_requests.py", line 221, in request
  File "adafruit_esp32spi/adafruit_esp32spi_requests.py", line 165, in request
  File "adafruit_esp32spi/adafruit_esp32spi_socket.py", line 76, in connect
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 572, in socket_connect
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 503, in socket_open
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 299, in _send_command_get_response
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 261, in _wait_response_cmd
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 171, in _wait_for_ready
ReloadException: 
soft reboot
```

I am seeing this in the output roughly 4 out of 10 times I run the code on a PyPortal w/ v3. I am simply running the example code from the module with no modifications except the light name. I am not even sure this is a bug in the code and not some strange network issue. What is bothering me though is the not finding the ssid line. I have other circuitpython devices not using the wifi manager and they have no issues over a 24h period were I saw the above issue many times. As the above second example shows, the code still works and the light triggers just fine, possibly because of it working on a second attempt at connecting to the ssid.

I am attempting to work my way back into the wifi manager as I think the bug/issue, if there is one, is there and not in the module.

Will continue to update this as I figure it out and if needed will take it to discord.

**Comment by mattyjones** [comment]
Closing this, I found the issue in the wifimanger and will work through it there.
